//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barb.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTible
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialTible()
        {
            this.UcherTable = new HashSet<UcherTable>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IDProizvoditel { get; set; }
    
        public virtual ProizvoditelTable ProizvoditelTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcherTable> UcherTable { get; set; }
    }
}
