//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barb.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcherTable
    {
        public int ID { get; set; }
        public System.DateTime Datelspol { get; set; }
        public int IDSotrudnik { get; set; }
        public int IDMaterial { get; set; }
        public decimal Zana { get; set; }
        public int Kolvo { get; set; }
        public Nullable<decimal> Summa { get; set; }
    
        public virtual MaterialTible MaterialTible { get; set; }
        public virtual SotrudnikTable SotrudnikTable { get; set; }
    }
}
